### ISSUE TITLE
IntelliJ plugin throws InvalidConfig exception on detekt created config

### ISSUE THREAD

**Issue by grodin** [detekt/detekt-intellij-plugin#102]
## Observed Behavior
After installing the detekt Intellij plugin from the IntelliJ Marketplace, a project with the default `detekt.yml` generated by the `detektGenerateConfig` gradle task causes the IDE to report a fatal error in the detekt IDE plugin, which has a root cause of an `io.github.detekt.tooling.api.InvalidConfig` exception being thrown. The message of the exception indicates missing/unrecognised config properties.

My understanding is that this behaviour was introduced in detekt/detekt#2193 to the gradle plugin, to quite rightly fail the build if there is an unsupported property in the config. Does this behaviour make sense for an IDE plugin? My expectation was that I would still get some feedback from the IDE without having to manually run the `detekt` gradle task.

In any case, the latest version of the IDE plugin should probably not be crashing with the default config!

## Your Environment

* Version of detekt used: gradle plugin v1.13.1, intellij plugin v1.5.0
* Version of Gradle used (if applicable): 6.3
* IntelliJ IDEA Community version: 2020.2.1
* Link to your project (if it's a public repository): 

Detekt is awesome in general, really, really useful, so thanks a lot for all the work that's gone into it!

**Comment by schalkms** [comment]
Thanks for the nice feedback and the kind words! Feels good to know, that users actually like what has been build.
I transferred your issue into the corresponding IntelliJ detekt plugin repository.
The introduced behavior is fine for detekt native and is expected system behavior, as you rightly stated.

The plugin itself shouldn't crash. I agree with you.
For the IntelliJ plugin, there could be a wrapper around the exception. Presumably, this could be done in the following class or at a more central point. https://github.com/detekt/detekt-intellij-plugin/blob/4015b3f10edd445d85cfe04dba558c05f29ea606/src/main/kotlin/io/gitlab/arturbosch/detekt/idea/ConfiguredService.kt#L25

Maybe @arturbosch can chime in here. Do you have opposing views on how to handle this issue?
