### ISSUE TITLE
Plugin throws when using config made for newer version of detekt

### ISSUE THREAD

**Issue by Lafreakshow** [detekt/detekt-intellij-plugin#111]
Hello there,

### Some background

I usually point the IntelliJ plugin to the config file used by my Gradle builds and I also like to have all available rules in my config file, but using plugin version 1.6.1 in IntelliJ and Detekt version 1.15.0 in Gradle. I just recently upgraded my Gradle builds from 1.14.2 to 1.15.0 (including adding new rules to my config file) and that's when I started getting this issue.

### The Problem

The plugin helpfully reports some invalid properties:

```
Caused by: io.github.detekt.tooling.api.InvalidConfig: Run failed with 4 invalid config properties.
	- Property 'complexity>NamedArguments' is misspelled or does not exist.
	- Property 'potential-bugs>MissingWhenCase>allowElseExpression' is misspelled or does not exist.
	- Property 'style>RedundantHigherOrderMapUsage' is misspelled or does not exist.
	- Property 'style>UseIfEmptyOrIfBlank' is misspelled or does not exist.
```

First of all, serious props for the useful exception message. Those are way to damn rare.

As far as I can gather, this isn't unexpected. These are rules added after 1.14.2 (which the IntelliJ plugin seems to use) so it makes sense that they wouldn't be known to the version of Detekt used here. 

### My thoughts/suggestions

The obvious solution would be to build the plugin against a more recent version of Detekt but I wonder if there isn't a more permanent solution to this. Would it be possible to have the IntelliJ plugin optionally ignore invalid properties like this? I don't know if these invalid properties break the entire config parsing but it may be a decent idea to allow detect to work with config files with newer rules in them. 

Another option may be to allow the IntelliJ plugin to use the same Detekt binaries used by the Gradle Plugin but again, I don't know how practical/possible that is. I'm just throwing around some ideas.

For now, I think I can just remove these properties from my config file as I'm using the default value anyway. But it would be nice to at least have an easier way to realise the cause of this problem. While the exception message makes pretty easy to see what is going on, it was somewhat deeply buried in a call stack hidden in an IntelliJ Error. The most noticeable thing was Detekt simply not working.

---

Let me know if you have any questions or need further information.

PS: I wasn't entirely sure if it was better to bring this up here or over in the detekt repository, as the thing throwing here seems to be detekt itself and not the plugin. Let me know if you want me to bring the issue up over there too.

**Comment by rock3r** [comment]
Same thing just happened to me with 1.16.0. My two cents on a longer-term solution: maybe the Detekt ruleset in use could be defined in the config file, so that the Detekt plugin can pick it up and use the appropriate Detekt version. Or, at least, users could pick up the Detekt version to use in the plugin configuration UI?

**Comment by arturbosch** [comment]
Config validation was enabled with #103.
