### ISSUE TITLE
How to run the detekt plugin in Android Studio

### ISSUE THREAD

**Issue by zhi-liu-dev** [detekt/detekt-intellij-plugin#124]
Hi, there.
Just a silly question, I have installed the detekt plugin from the marketplace in the Android Studio and also enable it and tick "Enable Detekt", "Enable Formatting rules", "Build upon the default configuration" and "Enable all experimental rules". I also define the path for the Configuration File.

So what should I do next step for reviewing the related output of Detekt ? Just click the run or build? where is the output

Thanks a lot.

**Comment by cortinico** [comment]
> So what should I do next step for reviewing the related output of Detekt ? Just click the run or build? where is the output

You should see the Detekt reports inline in your code. The code that gets reported will be highlighted and you can use the quick edit menu to understand what is the error and how to fix it.
