### ISSUE TITLE
Store configuration file path as relative to the project root

### ISSUE THREAD

**Issue by rock3r** [detekt/detekt-intellij-plugin#135]
Right now, as of v1.17.1, the Detekt configuration path is stored as an absolute path. Given that the Detekt IJ plugin settings are per-project, and thus saved in `.idea/detekt.xml`, this prevents folks from sharing the Detekt plugin configuration with other devs by committing the `.idea/detekt.xml` file as that contains absolute paths which will only work for one user.

This would easily be solved by using relative paths instead, referred to the project root directory.

**Comment by BorzdeG** [comment]
used both 1.17.x and 1.18.0 (PR) - saved normally in the .idea/detekt.xml file: 
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DetektProjectConfiguration">
    <enableDetekt>true</enableDetekt>
    <buildUponDefaultConfig>true</buildUponDefaultConfig>
    <configPaths>$PROJECT_DIR$/detekt.yml</configPaths>
  </component>
</project>
```

There is only a problem with the file selector settings - it displays the full path to the file, not a relative

**Comment by rock3r** [comment]
It saves them as absolute paths on my computer, but maybe it's because I used the file picker

**Comment by BorzdeG** [comment]
I also use the file selection dialog 

![image](https://user-images.githubusercontent.com/2332528/129608499-fa6212a9-e26d-4484-aa87-38aec0e25cfa.png)

**Comment by rock3r** [comment]
Hm it's the same I've done, but I'm on Windows. Maybe that's the difference

**Comment by rock3r** [comment]
I can confirm that the issue is that the IDE expects paths to be stored in POSIX format and will automatically relativize them only if they are in that format. I'm taking care of this as part of the work I am doing for #231 and the larger UI overhaul.
