### ISSUE TITLE
question: what is this warning mean?

### ISSUE THREAD

**Issue by MisileLab** [detekt/detekt-intellij-plugin#136]
MagicNumber: This expression contains a magic number. Consider defining it to a well named constant.
What this warning mean and how can I fix it?

**Comment by cortinico** [comment]
That's a report for the detekt rule called `MagicNumber`. You can find the documentation for that rule here: https://detekt.github.io/detekt/style.html#magicnumber

There are also examples of snippet of correct/invalid code.
