### ISSUE TITLE
Making AutoCorrect refactor action easier to discover

### ISSUE THREAD

**Issue by simondean** [detekt/detekt-intellij-plugin#140]
Hi.  Thanks for Detekt.  Currently the Detekt plugin's AutoCorrect feature is quite hard to find.  I only found it after wondering whether the plugin had one (having used ESLint plugin for JavaScript before and using its auto-correct feature) and then searching the issue tracker on this repo for any signs of such a feature 😄 

A couple of things might help.  Adding something to the plugin description when installing the plugin that mentions the AutoCorrect action under the refactor context menu: 

![image](https://user-images.githubusercontent.com/190464/135428361-42360b3a-436c-4df5-8e18-36b6c40fb9f5.png)

Something else that might help is adding some text to the settings pane for the plugin that mentions the AutoCorrect action

![image](https://user-images.githubusercontent.com/190464/135428997-5d995483-cebc-4671-a931-82eda81fc54e.png)

**Comment by cortinico** [comment]
> Adding something to the plugin description when installing the plugin that mentions the AutoCorrect action under the refactor context menu:

@chao2zhang Do you have access to the JetBrains account where we can edit this?

**Comment by chao2zhang** [comment]
Hello @simondean , thank you for trying out Detekt plugin. I agree with you that the current plugin is not descriptive to new users.

However, particularly for auto correct, are you referring to the inline prompt in IDE to fix the code upon selection?

**Comment by chao2zhang** [comment]
Ah, I didn't realize that we have an option under IntelliJ -> Refactor -> AutoCorrect by Detekt rules

**Comment by arturbosch** [comment]
We now provide an intention to autoCorrect via Alt + Enter - #167
