### ISSUE TITLE
The configuration file supports the Https protocol

### ISSUE THREAD

**Issue by madroidmaq** [detekt/detekt-intellij-plugin#146]
As shown below,
![image](https://user-images.githubusercontent.com/6247142/140686590-12615028-f832-4130-a60c-306a9c3012a0.png)

**I tried to configure the remote file in IDEA and found that it is not supported. The error is as follows:**
![image](https://user-images.githubusercontent.com/6247142/140691060-c66fbf12-5307-42cf-9206-9ce80ee3f46e.png)

```
detekt plugin noticed some problems
Configuration file /Users/***/develop/workspace/MyApplication/https does not exist.
Configuration file /github.com/detekt/detekt/blob/main/config/detekt/detekt.yml does not exist.Skipping detekt run.
Open Detekt projects settings
```

This method is very needed in multi-project and multi-person collaboration scenarios, and I hope to support

**Comment by cortinico** [comment]
Yup this is not supported at the moment. PRs are more than welcome 👍
