### ISSUE TITLE
Provide ability to detect/select version of detekt to use

### ISSUE THREAD

**Issue by deeprim** [detekt/detekt-intellij-plugin#15]
Ability to select version of Detekt to use should be provided

**Comment by mikezx6r** [comment]
I'm not so sure this is a good first issue given that the Detekt dependencies are downloaded, and included in the plugin jar.

I've only just started looking at IntelliJ plugin creation as I'd like the plugin to have the latest version of Detekt (1.0.0-RC13 now).

This could work as long as plugins are allowed to download files/dependencies based on configuration changes, but that seems like a moderately risky feature to expose, and likely is only approachable by someone familiar with plugin development.

**Comment by arturbosch** [comment]
You are right, thats not an easy task. However good first issue also applies to experienced plugin authors :).
Yes, we must make sure to download the jars via https as to mitigate what happened [here](https://github.com/shyiko/ktlint/pull/332).

**Comment by arturbosch** [comment]
I will close this issue as I don't know if it is even allowed for idea plugin to download and extend the plugin over the internet.
Other code quality plugins as spotbugs, pmd and QAPlug bundle the wrapped tool itself.
Users could stop using this plugin if we download additional jars over the internet.
