### ISSUE TITLE
On Intellij IDEA preview 2021.3.2 gradle build files with false positive FinalNewline

### ISSUE THREAD

**Issue by rocketraman** [detekt/detekt-intellij-plugin#151]
On Intellij IDEA preview 2021.3.2, gradle build files seem to have a false positive FinalNewline warning from Detekt.

**Comment by chao2zhang** [comment]
@rocketraman 👋  Thanks for the bug report. Do you happen to know if this is new to 2021.3.2?

**Comment by rocketraman** [comment]
I believe it is.

**Comment by arturbosch** [comment]
Do you still get this error with 2022.1 ?
I checked two different `build.gradle.kts` files and no `FinalNewline` warnings.
Could also be a false positive from KtLint which got fixed with detekt 1.20?

**Comment by rocketraman** [comment]
I don't recall seeing this again.

**Comment by rovkinmax** [comment]
I have this problem in each `.kt` file. Im using AS Electric Eel (2022.1.1) Canary 8 and AS  Dolphin (2021.3.1) Beta 5 with the latest Detekt plugin version 1.21.0-RC2
