### ISSUE TITLE
which personal data is processed by this plugin ?

### ISSUE THREAD

**Issue by david-gang** [detekt/detekt-intellij-plugin#154]
When i want to install this plugin i get a popup from intellij with the following wording 

"using third party plugins may involve a plugin vendor processing your personal data" 

Then it writes that i should check with the plugin author which personal data is processed by the plugin.

So i am asking which if any data is processed by the plugin ?

Thanks

**Comment by cortinico** [comment]
> So i am asking which if any data is processed by the plugin ?

We're collecting no data at all, we're just wrapping Detekt to make it easier to run inside IntelliJ
