### ISSUE TITLE
Installation issue, plugin doesn't seem to be installed

### ISSUE THREAD

**Issue by CapnSpellcheck** [detekt/detekt-intellij-plugin#156]
After installing the plugin from the Marketplace, and closing and relaunching Studio, the plugin is not listed under installed plugins. I search for Detekt again and it shows Install button again. Further, no Detekt settings show up on the preferences window.

Using Android Studio Bumblebee | 2021.1.1 Patch 1 on macOS.

**Comment by arturbosch** [comment]
Hi,
were you able to reproduce this strange behavior?

Are there any errors thrown?
Is there something strange in the idea log (Action: `Show log in files`) ?

**Comment by CapnSpellcheck** [comment]
This isn't blocking me, I tried again a few times and restarted the app and eventually it worked.

**Comment by arturbosch** [comment]
I'm closing this as I do not think it did happen due to our plugin but an IDEA internal error.
Feel free to reopen if this happens again with a stacktrace in the idea.log file.
