### ISSUE TITLE
Add code assisting features for detekt configuration files

### ISSUE THREAD

**Issue by deeprim** [detekt/detekt-intellij-plugin#16]
Add code completion inside of detekt configuration files:

```yml
caret # on top level, completion should propose all rulesets (performance, comments, etc.)

performance:
  caret # list of available "performance" rules should be proposed here
```

"Quick Documentation" (`ctrl+q` by _default_ on win) action triggered upon a group, rule, or rule's option should show the corresponding description.

* [ ] implement code completion for detekt configuration files
* [ ] implement "Quick Documentation" action

**Comment by schalkms** [comment]
This one can be closed, since we now have code-assistance with the help of schemas.

Source & Guide: https://github.com/detekt/detekt/issues/3143
