### ISSUE TITLE
plugin marks whole file as warning

### ISSUE THREAD

**Issue by ArtsiomCh** [detekt/detekt-intellij-plugin#173]
See https://github.com/snyk/snyk-intellij-plugin/blob/5a9427fa0f11a4397a9a458b12090003a5e2df0e/src/main/kotlin/io/snyk/plugin/ui/toolwindow/SnykToolWindowPanel.kt

![image](https://user-images.githubusercontent.com/14268320/171901958-0191e117-6c6f-4bf9-948e-64a36fccf59b.png)

UPD Same for simple and small: https://github.com/snyk/snyk-intellij-plugin/blob/5a9427fa0f11a4397a9a458b12090003a5e2df0e/src/main/kotlin/snyk/common/AnnotatorCommon.kt

**Comment by arturbosch** [comment]
Thanks for the report.

This one seems easy to fix but is a bit tricky.
Normally we would just check if the reported `KtElement` of the detekt finding is a `KtFile` and act accordingly but as the kotlin intellij plugin is based on `kotlin-compiler` but detekt has to be based on `kotlin-compiler-embeddable` for Gradle and co, we can't access `Finding.entity.ktElement` or else the classloader will crash.

One idea I have is to check if the start and end offsets of the `Finding` are the same as the `PsiFile` and use a file level annotation.

**Comment by arturbosch** [comment]
Just prototyped an idea and it seems it works.
Maybe still a little too much attention grabing but better than before?

![2022-06-03T20:49:07,407094174+02:00](https://user-images.githubusercontent.com/20924106/171928820-c16ad0bc-0def-4e05-92f2-48dec88e1a34.png)

**Comment by SnyersK** [comment]
Is there a way to disable this new behaviour?
Or at least group them into one such (expandable) line?

Some older files with multiple formatting issues, stack a multitude of those yellow lines.
This doesn't leave much room to actually read code, so it's quite intrusive.

Aside from that, that settings wheel just shows an empty window.
Not sure if this is as expected?

an example:
<img width="1634" alt="Screenshot 2022-06-15 at 17 15 14" src="https://user-images.githubusercontent.com/9936455/173863507-35e62c5b-05d8-4661-a0d4-f1abe8211c2e.png">
