### ISSUE TITLE
File paths should be platform-independent

### ISSUE THREAD

**Issue by rock3r** [detekt/detekt-intellij-plugin#231]
Config file paths (and possibly other paths such as baseline) are stored in `detekt.xml` and read back as platform-dependent.

This means that if the `detekt.xml` is [shared in VCS](https://blog.sebastiano.dev/share-the-settings-with-the-whole-team-a-year-later/) for the whole team to use, and not everyone is on the same OS (mix of POSIX and Windows users) the paths will not work for some folks and they'll be bombarded by "file not found" notifications from the Detekt plugin.

The plugin should store paths in a platform-independent way and apply the correct separators at runtime.

**Comment by arturbosch** [comment]
Related https://github.com/detekt/detekt-intellij-plugin/issues/117#issuecomment-1206117093

Idea:
Use `TableView` instead of a single file chooser element in settings.
Save config paths as list.
Use a `ToolbarDecorator` provide add actions which trigger a file chooser dialog.

**Comment by rock3r** [comment]
I'm actually working on that. Hopefully will have a PR soon. Fighting a bit with IJ :)

**Comment by arturbosch** [comment]
> I'm actually working on that. Hopefully will have a PR soon. Fighting a bit with IJ :)

Ah, cool! Good that I read your comment before starting it too :).
I also fight a bit with IJ :) ->

**Comment by rock3r** [comment]
I have tried maintaining the forms, but yeah, it wouldn't work. I'm migrating to the Kotlin DSL — it should mostly be ok, there's only one or two minor things in the DSL that weren't available (according to the inspections) before 22.1, but they can be emulated decently enough. So far, I am keeping 20.3 as the minimum target version, although tbh I think we can increase up to 21.2 if needed, which would still support AS stable (Chipmunk). I will only do it if needed, though.

My (very much WIP) work is [here](https://github.com/detekt/detekt-intellij-plugin/compare/main...rock3r:detekt-intellij-plugin:improve-ui).

BTW on the topic of OS independence, I have asked and theoretically the only need we need to do is storing paths as POSIX, the IDE will take care of relativizing them (which currently only works on POSIX as we store paths on Windows as Windows paths which aren't supported properly).

**Comment by arturbosch** [comment]
> I have tried maintaining the forms, but yeah, it wouldn't work. I'm migrating to the Kotlin DSL — it should mostly be ok, there's only one or two minor things in the DSL that weren't available (according to the inspections) before 22.1, but they can be emulated decently enough. So far, I am keeping 20.3 as the minimum target version, although tbh I think we can increase up to 21.2 if needed, which would still support AS stable (Chipmunk). I will only do it if needed, though.

Yes please, if you are sure about Android lets go with 21.2.
`ui.dsl.builder` should be version 2 of Kotlin UI DSL ? So it can't work with 20.3 right?

> 
> My (very much WIP) work is [here](https://github.com/detekt/detekt-intellij-plugin/compare/main...rock3r:detekt-intellij-plugin:improve-ui).
> 
> BTW on the topic of OS independence, I have asked and theoretically the only need we need to do is storing paths as POSIX, the IDE will take care of relativizing them (which currently only works on POSIX as we store paths on Windows as Windows paths which aren't supported properly, see #135).

Looks good! If you open a PR I can write already some comments if you like (`treatAsWarnings = false`).

**Comment by rock3r** [comment]
@arturbosch I have a couple of questions for you, I pinged you on the Kotlin Slack, but I am not sure you actually use it. Let me know if you prefer other ways to get in touch.
