### ISSUE TITLE
AutoCorrect by Detekt Rules does nothing

### ISSUE THREAD

**Issue by JacksonD2** [detekt/detekt-intellij-plugin#333]
I am on an M1 Macbook Pro, running Android Studio version 2021.2.1 Patch 1. My Detekt version is 1.21.3.

I will see Detekt highlighting lines of code, but whenever I run "AutoCorrect by Detekt rules" nothing happens.

**Comment by schalkms** [comment]
Which rules did highlight code?
Please note that not most rules do **not** support auto-correct. Only some rules in the formatting rule set support auto-correct.

**Comment by arturbosch** [comment]
There are some rules marked as auto correctable in the plugin which are in fact not.
This should get corrected with the new release soon based on detekt 1.22.
