### ISSUE TITLE
Release a new version with support for config files with *.yaml extension

### ISSUE THREAD

**Issue by acanda** [detekt/detekt-intellij-plugin#362]
Would you mind releasing a new version with support for config files with *.yaml extension, see #300. I submitted a PR a bit over a month ago, you merged it and I have been waiting to use it ever since. I would really appreciate it.

**Comment by arturbosch** [comment]
Sorry, this issue sliped through.
I was waiting for the final 1.22.0 version of detekt to release a plugin version.
Next time I will look up into Beta releases with Intellij Plugins.
