### ISSUE TITLE
Custom rules integration to IntelliJ plugin?

### ISSUE THREAD

**Issue by mtiidla** [detekt/detekt-intellij-plugin#43]
I have created a custom detekt rule and integrated it into the CI process. I am also using the IntelliJ plugin for Android Studio which works like a charm highlighting the issues based on the detekt.yml configuration file.

I have tried to add my ruleset to that file with the following config:
```
my_project_detekt_rules:
  NoKoinExplicitReturnType:
    active: true
```
I have also selected the .yml file in the IDE plugin as the configuration file and can confirm it registers changes in the yml file (IDE won't show warnings on a issue if I disable it in the .yml file)

However, the IDE does not seem to pick up my custom rule to highlight the issues, is that even supported by the plugin, or how should I approach that?

Using version 1.0.1

First opened in https://github.com/arturbosch/detekt/issues/1864

**Comment by arturbosch** [comment]
Thanks for the feedback.
Yes, an input field is missing in the config which basically will delegate to `--plugins`.
