### ISSUE TITLE
Not working on new Intellij IDE UI

### ISSUE THREAD

**Issue by wallysoncarvalho** [detekt/detekt-intellij-plugin#458]
Hi, I'm using **IntelliJ IDEA 2022.3.1 (Ultimate Edition), Build #IU-223.8214.52, built on December 20, 2022**. I'm using the new UI and the plugin is not working. After I install it and restart the IDE it seems to uninstall by itself.

**Comment by arturbosch** [comment]
Hm, can you please verify it with another IJ Ultimate Version, 2023 EAP for example and with a IJ Community edition of 2022.3.1 ?

I'm always on the EAP editions with the new UI and it works flawlessly on my side:

![Screenshot from 2023-02-07 19-34-44](https://user-images.githubusercontent.com/20924106/217335101-5de36e53-c5e5-43f3-b1bc-d29f4a91f25a.png)
![Screenshot from 2023-02-07 19-34-24](https://user-images.githubusercontent.com/20924106/217335109-b3c21316-a9f9-4b2b-9fd8-98261912c5e8.png)
