### ISSUE TITLE
Max line length broken on 1.22.2-android

### ISSUE THREAD

**Issue by Sammekl** [detekt/detekt-intellij-plugin#464]
On the latest version 1.22.2-android of the plugin, the max line length gives false positives at around 120 characters even though my `.editorconfig` and detekt configuration yml specify 140 characters. Reverting back to 1.22.1-android resolves this issue.

If required I can create an example project for this

**Comment by arturbosch** [comment]
That's really strange. Yes, a reproducer project would be ideal thanks.

**Comment by Sammekl** [comment]
Hi @arturbosch I tried reproducing it in a new project with the same configs, but it worked fine.
After some investigating we found that removing the `detekt-configuration.yml` from Android Studio settings and applying it again, fixed the issue.

We haven't had this before so it's something that broke in the latest version. After re-applying, it works fine and updates to the configuration do to.

I think this issue can be closed
