### ISSUE TITLE
How to use 3rd party rules?

### ISSUE THREAD

**Issue by pokk** [detekt/detekt-intellij-plugin#474]
Just a quick question, if this place is not for the question, I will remove this.

I would like to set [Twitter-compose](https://github.com/twitter/compose-rules) rules on my AS IDE. My setting might be wrong, could you please let me know how to set it?

![2023-04-20-8-28-55](https://user-images.githubusercontent.com/5198104/233307523-cdd6764a-382f-4c16-b742-9e7adc16da23.png)

According to https://twitter.github.io/compose-rules/rules/#preview-composables-should-not-be-public, here is supposed to have a warning or error.

<img width="231" alt="2023-04-20-8-31-03" src="https://user-images.githubusercontent.com/5198104/233307858-ca692a96-c86f-4260-b041-d7505835286c.png">

**Comment by arturbosch** [comment]
Hi,
please try if the compose rule set works for you with the cli: https://twitter.github.io/compose-rules/detekt/#using-with-detekt-cli
You can use `--debug` to print the loaded rule sets.
When I include the compose rule set, detekt picks it up:
![Screenshot from 2023-04-20 20-41-04](https://user-images.githubusercontent.com/20924106/233458425-c73d5bd5-e2a3-4371-aab3-26b93f9152a5.png)

(However I do not have any compose project to test this, so it might be some rule configuration is missing or the compose rule set requires type resolution ?

**Comment by pokk** [comment]
@arturbosch 

Thank you so much for the quick reply.
I have tried the cli, and it does work well.
Just wondering that my setting might be wrong. If the detekt plugins has't support it. It might be a good feature for the plugin 🙇‍♂️

**Comment by arturbosch** [comment]
> @arturbosch
> 
> Thank you so much for the quick reply. I have tried the cli, and it does work well. Just wondering that my setting might be wrong. If the detekt plugins has't support it. It might be a good feature for the plugin bowing_man

I'm not sure if the intellij plugin now also reports the compose issue or just the cli?
If it does not, maybe you could setup a minimal project where I could take a look?

**Comment by pokk** [comment]
I will let you know after I check it if it does work or not. 🙇‍♂️

**Comment by pokk** [comment]
Interesting! I got the lint errors from the jar file for a new project without any other settings.

<img width="1101" alt="2023-05-03-2-55-16" src="https://user-images.githubusercontent.com/5198104/235824780-2bf9e57e-b3f8-4eac-98e8-642b19942ce3.png">

This is my setting

![2023-05-03-2-56-29](https://user-images.githubusercontent.com/5198104/235824853-90d9e1a9-324e-4adc-b3e3-4a8ba6c9e04d.png)

---

I added the `detekt.yml` together.

![2023-05-03-2-59-18](https://user-images.githubusercontent.com/5198104/235825131-57a3fe0e-ad17-43d8-a2ae-40cc44f6a8d9.png)

It works well, too!!! 👍

<img width="1112" alt="2023-05-03-3-00-06" src="https://user-images.githubusercontent.com/5198104/235825187-8a9a4d18-6b5d-4962-92de-5f4bd917dc94.png">

I was looking for this [rule](https://twitter.github.io/compose-rules/rules/#preview-composables-should-not-be-public), seems it has a `note` that I didn't pay attention to it. 🙏

After trying many ways, I figured out I added `baseline.yml` to 

![2023-05-03-3-10-47](https://user-images.githubusercontent.com/5198104/235826124-e64b4322-5274-48d4-93c4-2fe48d0dbc17.png)

```xml
<?xml version="1.0" ?>
<SmellBaseline>
  <Blacklist></Blacklist>
  <Whitelist></Whitelist>
</SmellBaseline>
```

Sorry for the dumb question here. Didn't use the correct way to import the rules. 🙇‍♂️
