### ISSUE TITLE
Auto-correct not working

### ISSUE THREAD

**Issue by ayush2297** [detekt/detekt-intellij-plugin#482]
I recently added the detekt in my kotlin spring boot project and ran `./gradlew detekt`. I received multiple warnings and did not want to resolve them manually. That's when i came across this intellij plugin. 
The autocorrect feature does not seem to be working. 
Example : I am getting a simple warning of `no new line at the end of the file`. When I run autocorrect through the IDE plugin, it does nothing. 

Please help as I am not sure if I am missing anything. Kindly, let me know if any further information is required.

**Comment by arturbosch** [comment]
Hi, have you enabled formatting in the settings?
Also please try the first two checkboxes and see what the log files are saying, is formatting loaded ? Are formatting issues shown in the ide ?

**Comment by ayush2297** [comment]
This helped, thanks! I thought the formatting would work right away. It started working after enabling formatting rules.
