### ISSUE TITLE
Consider "Add * finding to baseline" quick fix to have lower priority than built-in quick fixes

### ISSUE THREAD

**Issue by IlyaGulya** [detekt/detekt-intellij-plugin#487]
Currently if IDE provides a quick fix for some issues, detekt plugin puts "Add * finding to baseline" quick fix higher than built-in one.
I think this is not expected behavior for most cases.

Here's an example:
<img width="566" alt="image" src="https://github.com/detekt/detekt-intellij-plugin/assets/668727/a01a1223-90aa-4416-a740-87a2c5c965bd">

**Comment by arturbosch** [comment]
Thanks for the suggestion, this will be adjusted in the upcoming 2.0.1 release - currently awaiting approval.
