### ISSUE TITLE
TooManyFunctions - Plugin highlights whole file

### ISSUE THREAD

**Issue by pinkasey** [detekt/detekt-intellij-plugin#83]
If a file contains more than x (x=11 by default) functions -
the entire file is highligted.
For example:
![image](https://user-images.githubusercontent.com/1780369/79686647-a7a4af00-824a-11ea-981c-f9b1bd5aa012.png)

better places to put highlight on:
- first line in file
- first function over threshold
- every function over threshold - this way you get a visual on the scrollbar of how much of your file should be trancated/transfered...

My pick is `first line in file`.
To be fancy - this can be a configuration on the rule, but maybe that's too much and better to keep-it-simple.

**Comment by arturbosch** [comment]
Fixed in https://github.com/detekt/detekt/pull/2702
