### ISSUE TITLE
When enabling All Experimental Rules, No checkers highlight in Intellij

### ISSUE THREAD

**Issue by tyvsmith** [detekt/detekt-intellij-plugin#86]
On Detekt Plugin 1.1.0 under IJ 2019.3.4, when we select "Enable All Experimental Rules", no violations will appear. It works fine when it's off.

The Idea.log has nothing to indicate what's going on.

**Comment by schalkms** [comment]
Thanks for reporting that.

**Comment by arturbosch** [comment]
I couldn't reproduce this on 2020.1 or 2019.3.5 Community edition.
Which combination of the configuration/baseline file and/or plugins do you use?
Maybe it is a specific combination.
Any change you can reproduce this with newer versions?

**Comment by jchprj** [comment]
I encountered this issue, only uncheck the _Enable all experimental rules_, the plugin works. 
My version is: 

IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 18, 2019
Licensed to #########
You have a perpetual fallback license for this version
Subscription is active until May 1, 2021
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: CheckStyle-IDEA, Lombook Plugin, VisualVMLauncher, YourKit Java Profiler 2019.8-b110 Integration, com.dubreuia, detekt, in.1ton.idea.spring.assistant.plugin, org.intellij.plugins.hcl, org.intellij.scala, org.jetbrains.kotlin, org.jetbrains.plugins.hocon

**Comment by arturbosch** [comment]
Do you see any errors thrown in the status bar ?

When no issues get highlighting by detekt but you expect some, then it is often the case that some detekt rule crashed.

**Comment by jchprj** [comment]
@arturbosch I did not see any error thrown in status bar, as well as no error log in IDEA log when enabled experimental rules. When disabled the experimental rules, the highlighting appears in seconds.

**Comment by arturbosch** [comment]
@jchprj as a workaround you could activate all rules which are `active: false` by dafault in your config file. Maybe you could narrow down the to the rule which causes the highlighting to disappear.

**Comment by arturbosch** [comment]
Cannot reproduce.
