### ISSUE TITLE
Not compatible with Android Studio since version 1.0.0

### ISSUE THREAD

**Issue by WonderCsabo** [detekt/detekt-intellij-plugin#87]
The plugin marketplace only shows 1.0.0-RC2 as a version.

Moreover, when i trying to install the plugins from file, i got an error: plugin 'detekt' is incompatible with this installation.

I see this in the logs:

WARN - llij.ide.plugins.PluginManager - detekt not loaded: since build 193.0 > AI-192.7142.36.36.6392135 

I use Android Studio 3.6.3 which is the latest stable version of Android Studio.

**Comment by WonderCsabo** [comment]
I assume [this](https://github.com/detekt/detekt-intellij-plugin/commit/326429c3074da155d026c20ab3b3845dd5726360#diff-b6feedd615d9efdc91202895f32bdf6eR16) change caused this issue.

**Comment by arturbosch** [comment]
Thanks for the fix!

**Comment by 4brunu** [comment]
@arturbosch could you please release a new version when you have some time, to allow the installation of this plugin in Android Studio?
Thanks 🙂

**Comment by arturbosch** [comment]
Sure, will upload it today after update to detekt 1.9.1. expect the new version to be verified and land in the plug-in store on round about 2 days 👍

**Comment by 4brunu** [comment]
Thank you 👍

**Comment by arturbosch** [comment]
Version 1.2.0 was published, available at bintray and github now and in intellij marketplace in a few days partying_face

**Comment by 4brunu** [comment]
Nice! Thanks for resolving this issue so quickly 👍
